### ISSUE TITLE
$global:config

### ISSUE THREAD

**Issue by brianbunke** [WahlNetwork/Vester#13]
Defining globally-scoped variables always makes me feel a little dirty. I dug into the code and think a quick change in each file would remove the current need.

Delete-Snapshot, for example:

```
Process {
    # Variables
    Invoke-Expression -Command (Get-Item -Path $Config)
    [int]$snapretention = $global:config.vm.snapretention

    # Tests
    Describe -Name 'VM Configuration: Snaphot(s)' -Fixture {
        foreach ($VM in (Get-VM -Name $global:config.scope.vm))
```

...would become:

```
Process {
    # Tests
    Describe -Name 'VM Configuration: Snaphot(s)' -Fixture {
        # Variables
        . $Config
        [int]$snapretention = $config.vm.snapretention

        foreach ($VM in (Get-VM -Name $config.scope.vm))
```

Of note:

1. The Invoke-Expression/Get-Item can just be dot-sourcing to grab its $config variable
2. Variables defined outside of the Describe block aren't allowed to sit at Pester's lunch table

I'm happy to submit the proposal as a pull request if there's agreement.

**Comment by chriswahl** [comment]
Closed by #16
