### ISSUE TITLE
-Config parameter in tests

### ISSUE THREAD

**Issue by brianbunke** [WahlNetwork/Vester#14]
Is there a need for the user to define -Config? I don't think it's a stretch to call it directly from `"$PSScriptRoot\Config.ps1"` in each test, and scold the user in the event of moving it out of the same directory.

Just to be up front about the real reason behind opening this issue. The current Invoke-Pester examples with the nested hashtables are ugly, and impossible to discover if you don't know to scroll down the Github readme. Removing the need for both variables to be supplied in that fashion would be amazing, but this issue is focused on the easy one. :)

**Comment by chriswahl** [comment]
The reason I left a `Config` param in there is for larger environments with multiple different configurations (ex: prod, pre-prod, dev, etc.). I could just let it find the default `Config.ps1` file if nothing is passed, but I was concerned that a newbie would leave this off the first time and not realize that it was a configurable option.

Alternatively, I could just say that if nothing is passed to `Config` that it finds the default, and if nothing is passed to `Remediate` that it defaults to $false.

**Comment by brianbunke** [comment]
This is interesting. I hadn't considered that use case. I really need a lab with multiple vCenters...the testing scenario seems to be following me around lately.

A few things come to mind:

1. I like the idea of setting default values for `Config` and `Remediate`. I haven't come up with a better solution than that yet. Allowing the functionality to just let a user `Invoke-Pester` -- and figure out the advanced stuff later, as needed -- would be really slick.
  1. If a new user does neglect to update the config file, the Invoke-Pester is just going to scream at them that there is nothing to connect to at 172.17.48.17. Hopefully. (Which maybe should have quotes, because it currently screams anyway after not interpreting that IP address correctly.)
2. The possibility of someone remediating against the wrong config file... :fearful: The way the module is currently structured, the only way to prompt "Remediating this $config against this $vCenter, are you sure?" is to do it for every single test, which is annoying.
3. The new `Config.Tests.ps1` assumes a single config file. That would need to be updated as well if the idea is to give the option for testing multiple.

2 is approaching something else that had occurred to me. I wonder if there should just be a master file that invokes all of the tests one by one. That solves two problems. First, you can ensure that `Config.Tests.ps1` always runs before everything else. Second, you could then throw a single `Confirm` at the user, instead of once for every test.

I don't know how that would work yet, but it's something I thought of back when I was figuring out whether the config validation would run first.

I'm going to submit a quick pull request to make a couple needed changes to `Config.Tests.ps1`, but the rest is up for debate.

**Comment by chriswahl** [comment]
Regarding your first item, I've added single quotes around the IP so that it gets through the tests properly.

However, I also split out the files into `Configs` and `Tests`. Otherwise, I can see this getting fairly messy in a hurry.

I've placed the `Config.Tests.ps1` file into the `Configs` folder. For me, it was causing issues because
1. Invoke-Expression isn't loading the config file (no path found, have been trying to debug but PowerShell is exceedingly poor at importing values from another ps1, sadly).
2. Statically defined config file. Need a way to allow someone to feed in a file (a file input param?).

**Comment by chriswahl** [comment]
Thoughts on wrong config file: that's what the `$remediate` bool is for. Try before you buy, set up a scheduled task once you're happy, and use a DVCS to control the source configs. :)

**Comment by brianbunke** [comment]
> I've placed the Config.Tests.ps1 file into the Configs folder. For me, it was causing issues because
> 1. Invoke-Expression isn't loading the config file (no path found, have been trying to debug but PowerShell is exceedingly poor at importing values from another ps1, sadly).
> 2. Statically defined config file. Need a way to allow someone to feed in a file (a file input param?).

I've got you covered here. The fix on 1 was what I was alluding to above, it needs to be dot-sourced now that I broke the $global: implementation. Submitting shortly.

**Comment by brianbunke** [comment]
I think I've got a lead on supplying defaults to each parameter. Opening a new branch, and should have something on that shortly.

**Comment by cars** [comment]
IFor background I'm looking at potentially running this against 30 vCenters so I need the ability to be able to specify the Config file when I invoke  because I might in addition to each vcenter need to be able to specify a different config file with VM settings for different sets of VMs....  it'd be nice if Config.tests.ps1 looked at the config file that's being passed in versus assuming it's the default one.

**Comment by brianbunke** [comment]
Attacked the above concerns with #18. That PR would allow a beginner to simply run

    Invoke-Pester C:\Vester\
    # or, assuming one has already Set-Location to the Vester directory,
    Invoke-Pester

**Comment by chriswahl** [comment]
With #18  you can now use

`Invoke-Pester -Script @{Path = '.\Vester\Configs'; Parameters = @{ Config = '.\Vester\Configs\SomeOtherConfig.ps1'`

Unless there's a more elegant way to pass the `config` param (Pester is a bit ugly on this).

**Comment by brianbunke** [comment]
After digging through Pester docs, it looks like that is indeed the easiest way to pass even a simple `-Remediate:$true`.

For others that stumble upon this in the future, reference Pester [#271](https://github.com/pester/Pester/issues/271) and [#423](https://github.com/pester/Pester/issues/423).

I think this is good to close?

**Comment by chriswahl** [comment]
Agreed.
