### ISSUE TITLE
Non-remediating tests?

### ISSUE THREAD

**Issue by brianbunke** [WahlNetwork/Vester#15]
Are you interested in adding non-remediating tests to the project, or would you prefer that -Remediate stays "global" against the test suite? I think any admin could be interested in things like "network adapters that aren't VMXNET3" or "disks that aren't thin provisioned," but those examples either incur downtime or aren't easy to fix in an automated fashion. Just wondering about your ideal scope. Thanks!

**Comment by brianbunke** [comment]
On further consideration, vCheck is already fairly adopted in the "passively report on potential changes" area, and your session looks like it's about automatic remediation anyway. :) Seems out of scope?

**Comment by chriswahl** [comment]
My opinion is that any test is a good test - perhaps start with non-remediating, and then add the code block to remediate later? Since you can pick and choose any test and flag it with the Remediate param, I think this makes sense.

**Comment by brianbunke** [comment]
Sounds good, closing this out. Consider adding something to the contribution section of the readme, if you get bored and don't want to answer this question in the future. :notebook:

**Comment by chriswahl** [comment]
Good call. I will do this.
