### ISSUE TITLE
Meaningful Test Failure Information

### ISSUE THREAD

**Issue by michaeltlombardi** [WahlNetwork/Vester#155]
When a specific test fails, readers of the output should be able to see what the actual discovered setting was and be able to understand why it failed the test to some extent.

## Expected Behavior
When reviewing a test failure, I get back the specific setting currently found for that test/target.
This helps me to drill down into the problem without having to go read the tests to see what it is doing.

A similar construct for this is used by DSC - you have the option to `get` information about infrastructure, the option to `test` if the infrastructure is in compliance, and the option to `set` the infrastructure such that it becomes compliant.

Vester lets us `test` and `set` but not `get` it looks like.

## Current Behavior
Using pester `v4.0.2`, all test failures return the same information:

```
      Expected: value to be empty but it was { }
      at line: 94 in C:\Users\lombarm\Documents\WindowsPowerShell\Modules\vester\1.0.1\Private\Template\VesterTemplate.Tests.ps1
      94:                         Should BeNullOrEmpty
```

Using Pester `v3.4.6`, all test failures return a similarly unhelpful response:

```
Expected: value to be empty but it was {@{InputObject=True; SideIndicator==>}}
   94:                         Should BeNullOrEmpty
   at <ScriptBlock>, C:\Users\lombarm\Documents\WindowsPowerShell\Modules\Vester\1.0.1\Private\Template\VesterTemplate.Tests.ps1: line 93
```

Neither of these options is particularly useful for troubleshooting.
Currently, if I need to investigate, I have to go run commands on my own after reviewing the test code to see what it was checking for specifically.

## Possible Solution
+ Modify `VesterTemplate.Tests.ps1 to return useful errors
+ Look to create specific error messages from within the tests themselves
+ Add a `get` type option for each test that returns the inspected value; pass that through the template tests on a failure.

## Context
I was hoping to be able to use the vester test suite + [reportunit](https://github.com/reportunit/reportunit) to provide a simple HTML5 dashboard for our engineers to be able to review, updating the dashboard on a schedule or letting them interactively pull the information.

Unfortunately, the value of the dashboard is largely around seeing the failing tests and being able to extract value from them. For some tests, this isn't a problem - I can guess that if a VM fails the `CDROM ISO File Test` what's going on there, but for others it means I have to go find the test, see what/how it's checking, and then do some further investigation _just to find out why the test failed_.

It's better if we can give the engineers the immediate information and context to go solve problems wherever possible.

## Your Environment
* Vester module version used: `1.0.1`
* PowerCLI version: `6.5.1.5377412`
* Pester version: `3.4.6` / `4.0.2`
* Operating System and PowerShell version: Windows `10.0.14393`, PowerShell `5.1.14393.1198`

**Comment by michaeltlombardi** [comment]
It looks to me like the problem mostly stems from the part of [VesterTemplate.Tests.ps1](https://github.com/WahlNetwork/Vester/blob/778047b16a776da943e7035702edf8337d15967c/Vester/Private/Template/VesterTemplate.Tests.ps1) that [performs the check without storing the result](https://github.com/WahlNetwork/Vester/blob/778047b16a776da943e7035702edf8337d15967c/Vester/Private/Template/VesterTemplate.Tests.ps1#L100-L101) and the [else section of the catch block](https://github.com/WahlNetwork/Vester/blob/778047b16a776da943e7035702edf8337d15967c/Vester/Private/Template/VesterTemplate.Tests.ps1#L113-L116) which throws the error itself rather than the context / output from `& $Actual`.

**Comment by brianbunke** [comment]
Old:

```
[-] Host esx01 - NTP Service Policy 4.87s
      Expected: value to be empty but it was { }
      at <ScriptBlock>, C:\Vester\Private\Template\VesterTemplate.Tests.ps1: line 101
      101:     Should BeNullOrEmpty
```

New, with #159:

```
[-] Host esx01 - NTP Service Policy 4.31s
      Desired:   [string]off
      Actual:    [string]on
      Synopsis:  Policy for NTP service (on,off,automatic)
      Link:      https://wahlnetwork.github.io/Vester/reference/tests/Host/NTP-Service-Policy.html
      Test File: .\Vester\Tests\Host\NTP-Service-Policy.Vester.ps1
      at <ScriptBlock>, C:\Vester\Private\Template\VesterTemplate.Tests.ps1: line 122
      122:     Throw $Message
```

👍 😃 👍
