### ISSUE TITLE
Invoke-Vester: Failed test runs `(& $Actual)` 2 additional times

### ISSUE THREAD

**Issue by Midacts** [WahlNetwork/Vester#163]
When running `Invoke-Vester`, if the test fails, it runs `& $Actual` two additional times in the `Catch` statement

## Expected Behavior

& $Actual should run only once

[Suggestion](https://gist.github.com/Midacts/5a749c6787d3c3da8abd766c72e19e40)

## Current Behavior

The test runs (& $Actual) once.
If the test fails, it reruns (& $Actual) two more time:
"Actual:    [$($(& $Actual).gettype())]$(& $Actual)"

Test run once

## Possible Solution

explained above

explained above

## Steps to Reproduce (for bugs)

Have any test fail. Running with `-Verbose` helps to see.
I found this on a "home grown" test that enabled SSH if it is not started (smartd / usbarbitrator test).
I saw it started/stopped SSH 3 times

1. Fail any test. Maybe use `-Verbose` for clarification

## Context

save time / cleaning the logic

gist provided above

## Your Environment

* Vester module version used:  latest
* PowerCLI version: latest (6.5.1?)
* Pester version: latest from PSGallery
* Operating System and PowerShell version: 2012 R2

**Comment by brianbunke** [comment]
👍 bug report, and the Gist looks good from here. Want to submit a PR?

**Comment by brianbunke** [comment]
Resolved in #165
