### ISSUE TITLE
Claim Rule Support / Complex Data Types

### ISSUE THREAD

**Issue by jeffgreenca** [WahlNetwork/Vester#174]
I want to open discussion on adding support for nmp satp rules and generally complex data.  We need it for enforcing vendor-specific configuration on our ESXi hosts.  But, this is a complex type of data to represent in our config file.  Here's a mock design, to get the conversation rolling:

```
nmpsatprule: { 
                    { Name: "VMW_SATP_ALUA", Device: "", Vendor: "IBM", ... },
                    { Name: "VMW_SATP_ALUA", Device: "", Vendor: "DEC", ... },
                    ...
             }
```

Pro: More or less follows current config file design
Con: All-or-nothing, if you are missing an individual claim rule, the entire test fails, without clearly indicating which claim rule is missing or present.

I'm looking for alternative suggestions, or improvements on this idea, before I get to coding this.

EDIT: More correct example.

**Comment by brianbunke** [comment]
Sorry for the delay, idly considered this off and on.

So basically, `$Actual` is going to construct something like a `PSCustomObject`, with a Vester test type to match?

Happy to hear from anyone else. All that said, I don't have a reason to say no. Go for it!

**Comment by jeffgreenca** [comment]
And... never mind.  PowerShell [hash tables ](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_hash_tables?view=powershell-5.1)work already.

In PowerShell:
```
[ScriptBlock]$Actual={ 
    @{"key1="value1", "key2"="value2" } 
}
```

Resulting Vester JSON config:
```
"Host":  {
    "datasample":  {
        "key1":  "value1",
        "key2":  "value2"
    }
}
```

So, I can just use that for the more complex datatypes.
