### ISSUE TITLE
vCenter Advanced Setting tests

### ISSUE THREAD

**Issue by jpsider** [WahlNetwork/Vester#183]
## Expected Behavior
Adding new vCenter advanced settings. There are A LOT!

## Current Behavior
All standard naming scheme.

## Possible Solution
Not all advanced settings were added, handful had errors.  

## Context
I used New-VesterTest.ps1 to generate these tests.

## Your Environment

* Vester module version used: 1.2.0
* PowerCLI version: 6.5.2
* Pester version: 4.0.8
* Operating System and PowerShell version: Win10, PS5

**Comment by brianbunke** [comment]
Based on the context, I'm closing this and pointing discussion toward #147. It's about time I finally got around to addressing that question. 😃
