### ISSUE TITLE
NFS performance

### ISSUE THREAD

**Issue by cars** [WahlNetwork/Vester#21]
So even though I can now use tags to exclude the NFS tests in my environments. I'm wondering if NFS seems really slow for others that do use it? 

I've been playing with the NFS Test and it's averaging 65-70 seconds (yes seconds not ms) per host in an environment that doesn't use NFS. Wondering if same is true for others?  I've made some changes to the test that seem to get it down 10-12 seconds per host but wondering if this something specific to my environment or not? 

-CRT

**Comment by chriswahl** [comment]
It only takes a few seconds for me. Might be a bit of both? The tests certainly go slow for me if I'm over a VPN.
```
Describing Host Configuration: NFS Advanced Configuration
 [+] esx01.rubrik.demo NFS Settings 3.65s
 [+] esx02.rubrik.demo NFS Settings 2.68s
 [+] esx03.rubrik.demo NFS Settings 2.64s
 [+] esx04.rubrik.demo NFS Settings 2.73s
 [+] esx05.rubrik.demo NFS Settings 2.64s
 [+] esx06.rubrik.demo NFS Settings 2.58s
Tests completed in 16.93s
Passed: 6 Failed: 0 Skipped: 0 Pending: 0 Inconclusive: 0
PS E:\vester>
```

**Comment by cars** [comment]
Here's an example of  what I get on my large environment.. . I'll have to try it against one of the smaller ones next week and see if maybe it's a function of the size of the environment. 

PowerCLI H:\src\github\Vester\Tests> invoke-pester  -Tag nfs -Script @{Path = ".\"; Parameters=@{Remediate = $False; Config = "H:\Config-Perms.ps1"}} -OutputFile h:\P01.xml -OutputFormat NUnitXml


Describing Host Configuration: NFS Advanced Configuration
 [-] esx-dc-0080.corp.com NFS Settings **_173.57s_**
   Expected: {20 30 32 32 1536 256}
   But was:  {12}
   32:                     $value | Should Be $compare
   at <ScriptBlock>, H:\src\github\Vester\Tests\Update-DNS.Tests.ps1: line 32
 [-] esx-dc-0076.corp.com NFS Settings **_65.13s_**
   Expected: {20 30 32 32 1536 256}
   But was:  {12}
   32:                     $value | Should Be $compare
   at <ScriptBlock>, H:\src\github\Vester\Tests\Update-DNS.Tests.ps1: line 32
 [-] esx-dc-0085..com NFS Settings **_65.88s_**
   Expected: {20 30 32 32 1536 256}
   But was:  {12}
   32:                     $value | Should Be $compare
   at <ScriptBlock>, H:\src\github\Vester\Tests\Update-DNS.Tests.ps1: line 32
 [-] esx-dc-0084.corp.com NFS Settings **_69.02s_**
   Expected: {20 30 32 32 1536 256}
   But was:  {12}
   32:                     $value | Should Be $compare
   at <ScriptBlock>, H:\src\github\Vester\Tests\Update-DNS.Tests.ps1: line 32
 [-] esx-dc-0088.corp.com NFS Settings **_68.42s_**
   Expected: {20 30 32 32 1536 256}
   But was:  {12}
   32:                     $value | Should Be $compare
   at <ScriptBlock>, H:\src\github\Vester\Tests\Update-DNS.Tests.ps1: line 32

So gist of it is, it might be worth me seeing if I can speed up the test......

**Comment by brianbunke** [comment]
It's still the slowest performing test in my experience, but I don't get anything close to your numbers.

    PS C:\> Invoke-Pester C:\Github\Vester -Tag nfs

    Describing Host Configuration: NFS Advanced Configuration
     [-] esxi01 NFS Settings 2.64s
       Expected: {20 30 32 32 1536 256}
       But was:  {12}
       32:                     $value | Should Be $compare
       at <ScriptBlock>, C:\Github\Vester\Tests\Update-NFS.Tests.ps1: line 32
     [-] esxi02 NFS Settings 1.99s
       blah blah blah
     [-] esxi03 NFS Settings 2s
       blah blah blah
    Tests completed in 6.63s
    Passed: 0 Failed: 3 Skipped: 0 Pending: 0 Inconclusive: 0

Same times if I add the XML parameters. The only nested ForEachs I see are based on the NFS config values, static at six, so scaling on environment size would be really surprising. Interested to see what happens against your smaller environment.

**Comment by cars** [comment]
So in looking at three vCenters in one of my datacenters  I'm seeing wide variance. running 
essentially a get-vmhost, and then for the first 6 hosts do get-advancedsettings (which is what the NFS test does)

```
vCenter  | Num Hosts | Time to get - 6 
   1           |         26      |    5.7 seconds       
   2          |          32      |    25.4 seconds
   3          |       345       |    1 minute 5.9 seconds
 ```

**Comment by brianbunke** [comment]
Huh, weird. I couldn't replicate, even by piping Get-VM into Get-AdvancedSetting (only way I can even attempt to simulate your scale). But that doesn't matter, because we can totally kill off the repeated Get-AdvancedSetting calls anyway. Something like this immediately inside the $server ForEach?

    $GetAdvSet = Get-AdvancedSetting -Entity $server -Name @($nfsadvconfig.Keys) -ErrorAction SilentlyContinue

Threw in the ErrorAction because my 6.0 U2 doesn't even know about NFS.DeleteRPCTimeout...I'll open a different issue to discuss.

Anyway, definitely some optimization opportunities. You mentioned you'd already made some changes on your testing. You halfway to a PR already?

**Comment by cars** [comment]
I've opened a pull request... I moved the Get-AdvancedSettings calls outside of the IT block because this seemed to speed things way up.... 

# #24
