### ISSUE TITLE
NFS.DeleteRPCTimeout

### ISSUE THREAD

**Issue by brianbunke** [WahlNetwork/Vester#23]
Caveat: I don't use NFS in my environments.

When I run the following command, I don't see `NFS.DeleteRPCTimeout` anywhere. 6.0 U1 & U2.

    Get-VMHost '*01*' | Get-AdvancedSetting | Sort Name

That key is one of the default NFS configuration settings in `Config.ps1`. Is it there, and I'm not cool enough to know about it? Can @chriswahl or anyone confirm that the key is returned when they run the above command on their environment?

**Comment by chriswahl** [comment]
It's an advanced configuration item that is added to work around this KB: https://kb.vmware.com/kb/1035332

I've found that most vendor solutions that support automatically adjusting NFS values on your hosts will create this key for you and populate it with the default of 30 seconds (int of 30).
