### ISSUE TITLE
NFS tests against value array

### ISSUE THREAD

**Issue by brianbunke** [WahlNetwork/Vester#27]
The NFS test, instead of testing that each actual value perfectly matches its Config counterpart, just makes sure that the actual value matches any one in the array of the six configured numbers. You can see this in the thrown error of a failed test:

    [-] esxi01 NFS Settings 815ms
      Expected: {20 30 256 32 1536 12}
      But was:  {8}
      43:                     $value | Should Be $compare
       at <ScriptBlock>, C:\Github\Vester\Tests\Update-NFS.Tests.ps1: line 43

A fix should correctly loop through the config values, testing them 1:1 against actual. (or vice versa)

This is super low priority, and maybe should just sit idle until the other NFS performance improvements are merged.

**Comment by cars** [comment]
So the question becomes does each setting become a test (i.e. IT block) similar to maybe the SSH tests... or  would it want to still be treated as a single test?

**Comment by cars** [comment]
There's also a PS module for pester  PesterMatchArray  (https://github.com/stuartleeks/PesterMatchArray) that could be leveraged.......

**Comment by brianbunke** [comment]
We can loop the array into It blocks, since it's just a simple "$x should be $y" for each of the six values. Should be pretty clean to implement. (After VMworld, haha)

**Comment by chriswahl** [comment]
I've merged in the new code in #26 because I'm seeing a 4x speed increase. If we want to try other variations on the test, I think they should be done against this new code that @cars wrote. Totally open to other ways to slice and dice the tests! :)
