### ISSUE TITLE
Storage Device Configuration

### ISSUE THREAD

**Issue by derfcat** [WahlNetwork/Vester#30]
First learned of this in the VMworld session today and I'd like to help out with extending the capability.  Right now, I have a need to continuously audit a 800+ host environment and part of that includes storage device configuration.  More specifically the path selection policy, round robin IOPS, and perennial reservation status.  Including these things in the current state of this project seems to require further scoping of host in config.  I was thinking a scope such as host.storage and move along the lines of how esxcli is constructed.

Any thoughts on expanding this project to include those storage device configuration pieces?  For my non-Auto Deployed hosts that run MSCS workloads, this would help get the information out of the host profile.

**Comment by chriswahl** [comment]
I think this is a valid test to include. We'd have to somehow find a graceful way to allow everyone to express the LUN information using a config file. I'm assuming that'd be the NAAs or WWNs? Or would you find some generic "make sure all LUNs of this naming style" are set to R/R or Fixed paths (examples)?

**Comment by derfcat** [comment]
I think it's be easiest with NAAs.  I can only speak from my experience on this, but LUN naming style wouldn't necessarily work.  The prefix on the NAA may indicate the storage the LUN is presented from, but it'd probably be better to create claim rules based on storage vendor and manufacturer if the that is the aim.  But to get back to the question...something like host.storage.<naa> and a hashtable of associated properties (again, like esxcli) is what I'm thinking.  It's easy to test and set via API that way.

**Comment by brianbunke** [comment]
I have no input up front...I don't see a problem with structuring the config that way. I'm interested to see a pull request!

**Comment by chriswahl** [comment]
I'd be interested to see a PR with an idea on this @derfcat ... I'm going to close the issue for now in anticipation of seeing some code samples. If you need to open this back up, feel free.

**Comment by derfcat** [comment]
Thanks, Chris and Brian.  I will get the code out this month, I just have to wait until I return home on 9/12.  Looking forward to the feedback.
