### ISSUE TITLE
Discuss tests against HA

### ISSUE THREAD

**Issue by equelin** [WahlNetwork/Vester#35]
I've submitted a PR (#34) for testing HA configuration but it needs to be improved to be usable. HA as a lot of options and we'll have to check the most of them.

Here are a list of functionality that should be tested:

- HA Admission Control
- Host Monitoring
- Datastore Heartbeats
- VM component protection
- Advanced Settings (streched cluster, etc...)

Is something missing ? Do you have any ideas/advices about how to test all of this ?

**Comment by mattallford** [comment]
At the risk of getting off topic for the specific HA tests, I think this brings up a point which may be worth a discussion, and that is how the tests are constructed. Should we have some guidelines around how many settings are checked within a single test, and when it is a good idea to build a separate test? I think we need to provide the user running Vester with the option to somehow easily exclude some of the checks within a test.

I guess by way of an example, lets look at Update-DNS.Tests. This test checks for two things:

- DNS Server
- DNS Search domains

What if there was a user that wanted to check for DNS Server config / drift, but not for DNS Search domains? Is this a risk if we build too many checks into ".tests" files? Happy to log this under a separate issue if it is deemed worthy of a discussion.

Back to the HA tests, as you have said there are a number of HA settings that we will want to provide the administrator the option of checking for, but before be dive too deep into that I think we should agree on the best way to bolt it all together. I think once we have this agreed, if we break up the sub-components of HA and have a few people tackle small components then it could get brought up to scratch quickly.

**Comment by brianbunke** [comment]
That's a fair concern, and I'd prefer to see a separate issue for further discussion.

**Comment by chriswahl** [comment]
I've opened #38 to discuss how we want to create more complex tests. I'd like to hold off on the HA testing for now until we have this figured out. Plus, it would be good to flesh out the Module fully first and then start adding more tests.
