### ISSUE TITLE
Complex Testing and Sub-Tests Discussion

### ISSUE THREAD

**Issue by chriswahl** [WahlNetwork/Vester#38]
As revealed with the HA tests, there are certain types of tests that end up being dependencies of themselves. As an example:
- Issue1:  HA should be on - as such, other settings should be configured such as Admission Control and Heartbeat Datastores
- Issue2: HA should be off - as such, other settings should not be tested because they are not applicable such as Admission Control and Heartbeat Datastores
- Issue3: HA should be on but we don't care about the other settings such as Admission Control and Heartbeat Datastores

Issue1 is relatively easy and is how Vester works today.

Issue2 could be solved in a few different ways. Probably the easiest is to simply wrap up the sub-tests (that check Admission Control and whatnot) with a boolean test to see if the user wants HA on in the first place. If HA enable $true, we run all the tests. If $false, we only check the state of HA.

Issue3 is a bit more interesting. There's a few ways we could handle this. One is to allow people to comment out configurations that aren't desired or perhaps set the value to $null. The Config.Tests file would need to allow for this. The .Tests file would need to then handle configs that are $null or missing and be told to skip those tests.

What say you @cars @equelin @brianbunke ?

**Comment by chriswahl** [comment]
After a discussion with @brianbunke we've come up with the following ideas:

* Tests will use `Describe` for each test instead of `It`. This allows the user to use tags and `TestName` params to filter out tests they don't want.
* By doing this, this solves the ability to use partial remediation by filtering tests based on tags or names. Example: DNS Server and DNS Search Domain could be independently remediated.
* This also solves the need to filter out configuration values that aren't interesting to the user. For example, we will provide default configuration values. If the user does not want to change these, and only wants to review specific tests, the user can filter based on tag/name and ignore the default configs.

**Comment by mattallford** [comment]
Thanks guys. This sounds pretty good to me, and it gives us a good framework to write the tests on, which will be scalable and easy for users to filter the tests they want.

For me, this now brings up another point around the tags, how they are used, and submitting requests for new tags. Are tags something we could include in the config file, and then reference from the .Tests, and possibly even use this as validation in the module that @brianbunke has worked on? I think this would provide us with a good baseline for what tags can be used within a test without getting 'tag sprawl'. Thoughts?

**Comment by cars** [comment]
We might want to as we get further along think about having some sort of taxonomy around tags so we don't end up with a hodgepodge. of tags..When i did the first pass I was thinking along the lines of the scope (vcenter, cluster, host, vm) and then a broad category...
For this we might want to keep it something like    ha-general and ha-specific as the tags, with general being the HA on/off test, and ha-specific  being the more specific tests?

**Comment by equelin** [comment]
So if i sum up everything with an example a test file will looks like this:

```Powershell
Describe -Name 'HA : State' -Tags @('Cluster','HA:State') -Fixture {
    It -Name "HA state is $hastate" -test {
        #Some tests
    }
} 

#If HA is enable, we can test it's configuration
If ($hastate) {
    Describe -Name 'HA : Admission Control' -Tags @('Cluster','HA:admissionControl') -Fixture {
        It -Name "Admission control state is $admissioncontrol" -test {
            #Some tests
        }
    }

    Describe -Name 'HA : Heartbeat Datastore' -Tags @('Cluster','HA:admissionControl') -Fixture {
        It -Name "Heartbeat Datastore configuration" -test {
            #Some tests
        }
    }  
}
```
Does it looks good to you ?

By the way, we could use this test structure into the Config.Tests.ps1 with the same tags, it'll allow to only run the relevant tests against the config file.

**Comment by cars** [comment]
I was thinking somehint more like: 
`Describe -Name 'HA : State' -Tags @('cluster','ha','ha-state') -Fixture {
    It -Name "HA state is $hastate" -test {
        #Some tests
    }
} 

#If HA is enable, we can test it's configuration
If ($hastate) {
    Describe -Name 'HA : Admission Control' -Tags @('Cluster','ha','ha-specifc') -Fixture {
        It -Name "Admission control state is $admissioncontrol" -test {
            #Some tests
        }
    }

    Describe -Name 'HA : Heartbeat Datastore' -Tags @('cluster','ha','ha-specific') -Fixture {
        It -Name "Heartbeat Datastore configuration" -test {
            #Some tests
        }
    }  
}`

Using the three tags for each Describe block  would make it easier to turn on or off all HA tests as well as allow one to be more selective. But I'm not sure I'd want to have a specific tag per test (i.e. ha:admissioncontrol, ha:heartbeat etc) unless there's an expectation that a lot of people would need to get that specific in tests.

Another idea for option three would be to use some keyword like "ignore" as the value to skip those tests for settings the user didn't care about?

**Comment by brianbunke** [comment]
Who's to say a user doesn't want to test the HA state _and also_ only one of the HA sub-tests? (Why is there no :shrug: emote?)

Personally, I'd rather solve these weird sub-test splits by either utilizing Pester's `-TestName` parameter, or by designing a different method altogether (as I'm contemplating in #29).

**Comment by cars** [comment]
I think using Pester's _-Tag or -ExcludeTag_ is a better choice than -TestName because that doesn't require people to dig into the tests to figure out what they do. While we've spent some time working on an adding/fixing tests and now that @chriswahl  has taken it public we want to think about folks who just want to get up an running and may not want or be able to dig into the individual test scripts...

Tags in this instance would  help balance out which tests get run versus having to break tests out into individual test scripts. Ie can have all the HA tests in one .ps versus having 6 (state, heartbeat etc...)

**Comment by equelin** [comment]
The problem of mixing `-Tag` `-ExcludeTag` or `-TestNames` is that it can overcomplicated the usage of Vester...

I was thinking at another solution, what if the config file is used to select wich test to run? if the user put some data in it, Vester run the tests related to this data. No data, no tests.
What do you guys think about that?

**Comment by cars** [comment]
@equelin I'm just not sure how you'd do that and yet keep things simple. It seems you'd need to either parse the tests to look for the tags to know what _not_ to run or have to have some sort of config file/layer that matches tests to config values? 

I'll just put it out there that I personally like the idea of tags since we're relying on Pester underneath and expecting people to write tests using Pester. I think if we're gonna do something else to match config values to tests it needs to be lightweight....

**Comment by equelin** [comment]
Sorry I should have provide examples... 

Here is a test file, I just added some If statement to check if a variable exist in the config file:

```Powershell
[CmdletBinding()]
Param(
    # Optionally fix all config drift that is discovered. Defaults to false (off)
    [switch]$Remediate = $false,

    # Optionally define a different config file to use. Defaults to Vester\Configs\Config.ps1
    [string]$Config = (Split-Path $PSScriptRoot) + '\Configs\Config.ps1'
)

Process {
    # Tests
    Describe -Name 'Testing code refactoring' -Tag @("Test") -Fixture {
        # Variables
        . $Config
        
        If ($config.test.var1 -ne $null) {
            It -Name 'Variable Var1 is present in the config file' -Test {
                $True | Should Be $True
            }
        }

        If ($config.test.var2 -ne $null) {
            It -Name 'Variable Var2 is present in the config file' -Test {
                $True | Should Be $True
            }
        }
    }
}
```
And, when invoke-pester will be 'alive' we could use tags but in a more automated way:

```Powershell
Function Invoke-Vester {
    [CmdletBinding()]
    Param ()

    . .\Configs\Config.ps1

    $TagList = @()

    If ($config.test) {
        $TagList += 'Test'
    }
    If ($config.test2) {
        $TagList += 'Test2'
    }

    Invoke-Pester -Tag $TagList
}
```

With this method we can:

- Test if a group of parameters exists ($config.host) and if true, run the Tests.ps1 file associated
- Test if a specific parameter exists ($config.host.searchdomain) and run the pester tests associated

I really like that the user has not to worry about parameters like `-Tag` or `-TestName`. He just has to focus on writing a good config file and Vester/Pester will run all the relevants tests.

**Comment by mattallford** [comment]
@equelin I don't actually mind the idea of the if statement to check if the user has entered something into the config file for a property before doing the test. We could then have instructions for the user to either comment out the config, or just simply leave it empty and it won't be tested.

I think this might also mean we can be more relaxed with the tags, and leave them at a higher level (such as 'HA', 'DRS', 'Cluster', etc). With that said, I still think we should get a consistent set of tags as an approved list to work off, and additions can be submitted if the need arises.

It's probably neither here nor there, but I'm not a huge fun of checking if a variable does not equal $null, rather simply just seeing if it is populated and if it is, run the It.

`        If ($config.test.var2) {
            It -Name 'Variable Var2 is present in the config file' -Test {
                $True | Should Be $True
            }
        }`

It would be pretty quick to fix up the existing tests and the template to allow for this as well.

**Comment by chriswahl** [comment]
I like the idea of having the `Invoke-Vester` module actually parse through the Config file to determine which tests to run. It creates a lot of code overhead (we have to parse through every single entry, determine if it has a value within a specific range, and then invoke a Pester test). But it also let's people declare their desired state in a fairly simple manner.

Tags would then continue to be a greater set of tests for more specific validation. I also like the idea of a limit of three tags - the major, minor, and detailed tags as @cars has exampled.

So, unless I'm mistaken, the consensus is around these ideas for the future architecture:

* Configuration values can be commented out or left empty.
* Vester (the module) will parse through the config and either a) skip tests for undefined config values, or b) make sure the defined value for a config is valid and proper and then run the test.
* Tests will continue to gather the data they need, and then filter through the data for the `Describe` blocks.

**Comment by brianbunke** [comment]
That summary sounds reasonable to me!

**Comment by equelin** [comment]
I'm ok with that too.
@brianbunke  I've started myself some tests around Invoke-Vester. I'm available for discussions on that topic!

**Comment by cars** [comment]
@brianbunke  @equelin It'd be nice to see an option for people to be able to add/specify Tags  in `Invoke-Vester` for stuff that's not in the config file. I'm working on stuff around auditing permissions/roles that may or may not see the light of day outside my environment where I want to use Tags to have it run certain tests that may not be in the main branch.....  So it'd be nice to be able to say essentially look at the config file but also run this other thing.... Though if that proves to be difficult or an edge case, I could always just run Pester directly....

**Comment by cars** [comment]
Also @equelin  it might be worth considering something like: 

```
Function Invoke-Vester {
    [CmdletBinding()]
    Param ()

    . .\Configs\Config.ps1

    $ExcludeTagList = @()

    If (-not $config.test) {
        $ExcludeTagList += 'Test'
    }
    If (-not $config.test2) {
        $ExcludeTagList += 'Test2'
    }

    Invoke-Pester -ExcludeTag $ExcludeTagList
}

```
Just wondering if its easier/faster  to hand Pester a shorter list of things to not do than a whole bunch of things to do?

**Comment by brianbunke** [comment]
I'm a little lost...help me understand, @cars. You are trying to test things that wouldn't have values in the config file? How would we tell Vester what to check for?

Today, there are no tests or config values for permissions/roles. Are you saying you have private tests with predefined values that you want to run occasionally, and tags would be a way for you to do that?

Just trying to wrap my head around exactly the use case, so we can figure out how to address it.

**Comment by cars** [comment]
@brianbunke  In a pre-` Invoke-Vester` world I'd drop the test scripts into whatever folder I pass in to `invoke-pester`  and they would just get run with everything else in that directory. Or I could specify `Invoke-Pester -Tag roles` to just run those tests.  Today the config tests just checks the config file for things it knows about, it doesn't control what tests actually get run, that's handled by Pester and the input path.  In my case I  would add things to the config file, but they would be "extra" and wouldn't be checked for in Config.tests.ps1.  Example:
```

<############################################################################
        Roles and Privileges Settings
        Leveraging vCenter-Roles from https://github.com/rnelson0/vCenter-roles.
#>
$global:config.roles= @{
   vcenterrolespath = "H:\Src\github\vcenter-roles"
   defaultRoleFilePath = "H:\src\github\vcenter-roles\roles"
    rolesPresent = @{"loginsight"    = "loginsight3.json";
                     "vestertest"    = "H:\Vestertest.json"
                     "rubrik"        = "rubrik.json"
    }
    Present = @("Administrator","logInsight","VesterTest","rubrik")
}

```

Does that help?

**Comment by chriswahl** [comment]
This thread is reasonably old ... I think we've got the architecture baked quite well in the `module` branch today. I will close this thread and if further discussion is required we can re-open.
