### ISSUE TITLE
Discussion - Promoting Module to Master

### ISSUE THREAD

**Issue by chriswahl** [WahlNetwork/Vester#67]
I'm curious what everyone thinks is remaining to retire the current `master` branch and focus efforts on the `module` branch (thus making it `master`). I tend to support a "just enough functionality" model in which we start with a few tests and grow from there, even if we don't have test parity with the current `master` branch.

So - what are the big blockers preventing us from using the module today? @cars @equelin @brianbunke @mattallford 

Also, I'm not a huge fan of the Project tab. Seems like too much overhead.

**Comment by brianbunke** [comment]
I can't think of anything blocking us from publishing today. The items on my list won't change end-user functionality, and therefore could be implemented at any time.

I'm primarily thinking about adding unit tests to help automate PR testing, both for the core commands and some basics to hit for new test contribution.

Porting the current test suite is definitely a short-term item as well, but I think my time would be better spent setting up the unit tests. (And, from my seat, having others converting tests to the new format is probably a good exercise...both to ensure they're intuitive, as well as spreading the expertise among multiple people.)

**Comment by equelin** [comment]
I definitly agree that the module is ready to be released. We should focus now on adding new tests and promote Vester to have quick 'users' feedback.

Again, really good work guys !

**Comment by chriswahl** [comment]
Agreed. I can focus on getting new tests written. I had tried with DRS but
ran into that enum bug. :-)

**Comment by chriswahl** [comment]
Merged. https://github.com/WahlNetwork/Vester/commit/846046de3472a2162054187462c23678830d4e17

**Comment by chriswahl** [comment]
I've also uploaded Vester to the PowerShell Gallery! Primarily to hold our name. :)

https://www.powershellgallery.com/packages/Vester/1.0.0

**Comment by mattallford** [comment]
Awesome stuff guys. I haven't had enough time to go thoroughly through it, but initially it has worked OK for me, so it is awesome to see the module become the master.
