### ISSUE TITLE
Creation of Unit Tests

### ISSUE THREAD

**Issue by chriswahl** [WahlNetwork/Vester#69]
Need unit tests for the various tests found within the module. The lead contributor on this is @brianbunke but marking this as help wanted to attract the various crawler engines out there.

**Comment by equelin** [comment]
@brianbunke , I was planning to add some unit tests about fonctions parameters, are you interested ?

Basically it looks if the parameters are presents in the param () block and if the types are correct.

**Comment by brianbunke** [comment]
Sounds good, go for it! Let me know if you need anything.

**Comment by brianbunke** [comment]
Current progress:

✔️ Verification of module and related helper files
➖ Recursive `.Vester.ps1` test verification (Bon Jovi would say we're halfway there)
❌ Exhaustive unit testing of public functions (`Invoke-Vester`, `New-VesterConfig`)

I'm leaving the public functions for last. @equelin: will you have something I can work off of, were you waiting for me to put something in, or maybe thinking something else entirely?

**Comment by equelin** [comment]
@brianbunke Please look at the PR #76 ;-)

**Comment by brianbunke** [comment]
PR #77 to cover most of this. I'll still need to iterate on the tests for `Invoke-Vester` & `New-VesterConfig`.

**Comment by brianbunke** [comment]
PR coming this weekend...finally

**Comment by brianbunke** [comment]
Tracking in #86. IMHO, resolved.
