### ISSUE TITLE
Updated Module docs

### ISSUE THREAD

**Issue by chriswahl** [WahlNetwork/Vester#70]
Now that we have a full fledged module for Vester it's time to get the README.MD file updated. Most of this has already been done by @brianbunke in the about_help file and within the code itself. Just need it to all match on the project page + code itself.

Would also really like to get the help put into Markdown files so that we can start using `ReadTheDocs` to auto generate docs.

**Comment by equelin** [comment]
@chriswahl Did you look at [PlatyPS ](https://github.com/PowerShell/platyPS) ?  It could help for automated the generation of the markdown files.

**Comment by chriswahl** [comment]
I just write them by hand. :) But I will!

Also, note to self, we now have a Slack channel on VMware {code}. Need to drop that into the docs.

**Comment by equelin** [comment]
Handcrafted help files are nice too ;-)

I'm using PlatyPS on another project, I like the integration with [readthedocs](https://readthedocs.org/). 

Example: http://unity-powershell.readthedocs.io/en/latest/References/Connect-Unity/

**Comment by chriswahl** [comment]
I've created a ReadTheDocs page [here](http://vester.readthedocs.io/en/latest/index.html). For now I've copied over the existing `README` file data and have shortened the `README` to point to RTD.

**Comment by chriswahl** [comment]
I've put together a new version of the docs based on the help written by @brianbunke - you can find it in the `update-docs` branch [here](http://vester.readthedocs.io/en/update-docs/index.html)

**Comment by brianbunke** [comment]
@michaeltlombardi expressed interest in Slack about helping us on #104. It would involve a file format conversion from RST to Markdown, which I approved.

Commenting here as a format change FYI, taking a gratuitous opportunity to praise @michaeltlombardi (:clap:), and hoping that tagging him publicly helps him follow through and deliver where we have so far failed to 🙂

**Comment by brianbunke** [comment]
Referencing #158 & #160:

GitHub Pages now watches the new `gh-pages` branch to automatically generate https://WahlNetwork.github.io/Vester from its contents. This would render the ReadTheDocs page obsolete, and require a quick update of the project's readme.

We should have "set up an automated pipeline" (I'm most familiar with AppVeyor atm) on the roadmap.

How's this look/sound, @chriswahl?

**Comment by chriswahl** [comment]
Automation is joy. Sounds good to me ... let me know when the RTD page is no longer referenced and I can update the page or just take it down.
