### ISSUE TITLE
Auto-Import of VMware.VimAutomation.Core

### ISSUE THREAD

**Issue by brianbunke** [WahlNetwork/Vester#74]
So, 1cebb28 ("Move VMware module to external dependencies for PoSh Gallery") introduced an interesting problem.

When `VMware.VimAutomation.Core` was a "Required Module," I could open a console and do this:

    Import-Module .\Vester
    # Note that VMware.VimAutomation.Core automatically loaded as part of the Vester import
    Connect-VIServer vcsa.home.lab

Now, after moving to an "External Module Dependency," it doesn't work:

    Connect-VIServer : The term 'Connect-VIServer' is not recognized as the name of a cmdlet, [blah blah blah]

Furthermore, Door A:

    Import-Module .\Vester
    Connect-VIServer vcsa.home.lab

    Connect-VIServer : The term 'Connect-VIServer' is not recognized as the name of a cmdlet, [blah blah blah]

    # Fine, I'll manually import
    Import-Module VMware.VimAutomation.Core
    Connect-VIServer vcsa.home.lab

    Connect-VIServer : The term 'Connect-VIServer' is not recognized as the name of a cmdlet, [blah blah blah]

And Door B:

    # Guess I'll try bringing in PowerCLI first?
    Import-Module VMware.VimAutomation.Core
    Import-Module .\Vester
    Connect-VIServer vcsa.home.lab

    # lol jk I'm fine

Any quick suggestions on how we should ideally handle this within the `.psd1` file?

**Comment by brianbunke** [comment]
Both "doors" above also return inaccurate results for `Get-Command -Module Vester`

**Comment by chriswahl** [comment]
I'm not sure on a quick fix unless the PowerCLI code is added to the Gallery. Otherwise, having it as a dependency makes the Gallery upload fail (can't find the module ... abort).

Would a #requires statement not work?

**Comment by brianbunke** [comment]
#78 works for me with PowerCLI 6.3 and 6.5.

**Comment by chriswahl** [comment]
Merged. That works for me, too. And I agree that we should continue to encourage people to use the latest version of PowerCLI. Especially since VMware officially recommends that.
