### ISSUE TITLE
JSON config conversion fails in some instances

### ISSUE THREAD

**Issue by kxrobert** [WahlNetwork/Vester#75]
Attempting to run the code with PSVersion 4.0 on Win Server 2012 R2. Line 146 in invoke-vester needed to be updated to "$cfg = Get-Content $ConfigFile -raw| ConvertFrom-Json" for conversion to complete. -RAW was not needed when running on Windows 10 with version 5.0 but was compatible with both versions.

**Comment by brianbunke** [comment]
Replicated in v3/v4 on 08/12. Confirmed that `-Raw` works in all those scenarios, and is still compatible with v5 as stated above. Thanks @kxrobert!

Fix added to open PR #73.

**Comment by brianbunke** [comment]
Guess that's a premature close. I'll leave it open until the PR is merged, in case others wander over here with the same problem.
