### ISSUE TITLE
Slack channel

### ISSUE THREAD

**Issue by equelin** [WahlNetwork/Vester#79]
What do you think about creating a slack channel for Vester ? It'll allow to discuss more freely than on GIthub's issues and emojis are way cooler on slack (:parrotparty: !!!)

VMware {code}'s slack could be a good choice.

**Comment by chriswahl** [comment]
I don't think I have access to that Slack - do you? I'm fine with having a Slack channel. We'd need to update the readme to direct folks there.

What does everyone else think? Is this something that would help?

**Comment by brianbunke** [comment]
I've thought about creating that channel, just didn't know if we needed it or how useful it would be. I'm fine with jumping in there.

https://code.vmware.com/slack/ also has the benefit of not hiding your messages every week because the 10k limit is reached so quickly.

**Comment by mattallford** [comment]
A slack channel could be pretty helpful, I'm for it. Could help drive a lot of ad-hoc discussion and bouncing ideas around.

**Comment by chriswahl** [comment]
Done. There's now a #Vester channel in VMware {code} slack.
