### ISSUE TITLE
Config Validation Check

### ISSUE THREAD

**Issue by chriswahl** [WahlNetwork/Vester#8]
Need to create some method to validate:
1. That the config file has valid params defined
2. That the param values are within some sort of range

Optionally, it would be nice to accept a range of inputs and auto-generate a config.

**Comment by equelin** [comment]
Just thinking out loud but why not using Pester tests to check if the config file is valid? 

Maybe 2 downsides:

- As far as I know, you can't easily ordered the tests with Pester. Ideally, config test should be run first
- It doesn't allow you to auto-generate a config...

**Comment by chriswahl** [comment]
That's certainly one idea. Although I'm not a fan of using a system to test ... itself? I'm thinking to use the `Param()` details to set validation on the variables, which would be the guardrails, and also ensure they are not null.

**Comment by equelin** [comment]
Or a helper function called with the `ValidateScript` option in the param()

```Powershell
Param (
    [Parameter(Mandatory = $true,Position = 1,HelpMessage = 'Path to the configuration file')]
    [ValidateScript({Test-Config -Config $_ })]
    [string]$Config
)
```

**Comment by brianbunke** [comment]
Butting in here out of left field. :)

I've uploaded #12 as a possibility to validate config values without affecting the rest of the ecosystem. Feel free to accept/reject it as you see fit.

@equelin Calling Invoke-Pester on a folder seems to take the tests in alphabetical order, which is a bit serendipitous. Config.Tests.ps1 would always be the first to run in this scenario.

Another option would be to rethink the way the Config is defined, as alluded to above. For example, a (potentially?) more user friendly option would be to step through it with Read-Host and then validate along the lines of #12 's examples:

```
[string]$ScopeCluster = Read-Host 'Enter the cluster name(s) you wish to test, separated by commas [default is *]'
[string]$ScopeHost = Read-Host 'Enter the host name(s), separated by commas [*]'
[string]$ScopeVM = Read-Host 'Enter the VM name(s), separated by commas [*]'

$config.scope = @{
    cluster = &{If ($ScopeCluster) {$ScopeCluster} Else {'*'}}
    host    = &{If ($ScopeHost) {$ScopeHost} Else {'*'}}
    vm      = &{If ($ScopeVM) {$ScopeVM} Else {'*'}}
}

# Validate w/ Pester, possibly even loop back on bad input
# At end of script, export $config as desired to a file in the same directory
```

The Pester project uses Pester to Pester their Pester. I don't mean that in an authoritative "you have to accept this and get with the times" sense, I just liked the way it sounded and had to include it.

**Comment by equelin** [comment]
Wow very nice work @brianbunke !
