### ISSUE TITLE
Question about the NFC-UseSSL test

### ISSUE THREAD

**Issue by haberstrohr** [WahlNetwork/Vester#83]
In a previous PR I submitted NFC-UseSSL.Vester.ps1 that checks if config.nfc.useSSL is set to True or False. The odd thing about this setting is that the key its checking doesn't exist by default, and this may be a setting that few people care to enable. My new idea is that I add a few additional comments to the test itself explaining why it exists and how it can be used (what to add to config.json, etc.) as well as modifying the new-vesterconfig.ps1 file removing the following line so that value doesn't exist in the generated config.json file.

``` Powershell
nfcusessl = $vcenterHash['config.nfc.useSSL']
```

Thoughts? I don't want to force the hardening guide standards on people that don't want them and so far this is the only test that results in an error after the initial config.json file is generated followed by invoke-vester

**Comment by brianbunke** [comment]
Yeah, good question. I'll say this: for these values that don't exist by default, `New-VesterConfig` is properly populating them into `config.json` as `null`, which skips the test entirely.

To frame this as a decision for other interested parties:

1. Remove `NFC-UseSSL` from `New-VesterConfig` entirely
    - Test file contains additional comments for how to add the value if you want to test it
2. Leave this in `New-VesterConfig`, usually generating a null value
    - Potential of other tests being added for non-default values, increasing `config.json` size for a lot of null values

(Related #23, which isn't a problem right now only because the old NFS tests haven't been converted to the new format yet).

**Comment by haberstrohr** [comment]
In my testing it seemed that with a null value for the vcenter test (at least the NFC-UseSSL test) it would try to run the test and fail.

**Comment by brianbunke** [comment]
`null` in the config file better be skipping the test. If not, IDK what to think anymore. Would you mind confirming by running `Invoke-Vester` with the `-Verbose` flag?

**Comment by haberstrohr** [comment]
Setting null does skip the test. The issue was related to my trying to force the value as boolean, and null doesn't convert to a boolean value. Helps when you read the errors. :) 

Now that I'm getting more familiar with the test writing I feel comfortable leaving the NFC-UseSSL check in `New-VesterConfig`. The size of `config.json` has only increased 1kb or so with about 20+ tests, most of which are `null` by default.

**Comment by haberstrohr** [comment]
Closing this issue. With the changes in #88 this is no longer a concern.
