### ISSUE TITLE
404 Update-Template.ps1 Reference

### ISSUE THREAD

**Issue by jeffgreenca** [WahlNetwork/Vester#93]
I see that Update-Template.ps1 is no longer current, but still referenced in the documentation here http://vester.readthedocs.io/en/latest/contribution.html.  Can we get a quick update to the docs so it is apparent the broken link is a known issue, without digging through the other multi-paragraph issue?  

Also, let me know the appropriate etiquette for this kind of thing - am I supposed to just fork and submit a pull request to fix it myself?

**Comment by chriswahl** [comment]
Absolutely. Would love to see more work done on the documentation - you can reference #70 for that stream. Currently, I just ported our old docs to ReadTheDocs to lay the groundwork.

**Comment by jeffgreenca** [comment]
Fixed by #97
