### ISSUE TITLE
-WhatIf behavior depends on test

### ISSUE THREAD

**Issue by jeffgreenca** [WahlNetwork/Vester#96]
Running Invoke-Vester -Remediate -Whatif allows some changes to execute.  If $Fix code for a test uses cmdlets without -WhatIf support, real changes may be made.  For example, VIB-AcceptanceLevel.Vester.ps1 is susceptible to this problem due to its use of Get-EsxCli.

Rather than rely on each devs test to handle Should execution properly, I'm wondering if some wrapper logic would be appropriate before executing the $Fix block.  But I'm not sure how Pester handles that exactly so...

**Comment by brianbunke** [comment]
I'm unable to reproduce this. I tried the following and `-WhatIf` behaved as expected, preventing `$Fix` from executing:

```posh
Invoke-Vester -Remediate -WhatIf -Test .\Vester\Tests\Host\VIB-AcceptanceLevel.Vester.ps1
```

`VesterTemplate.Tests.ps1` wraps each `$Fix` call at line 101. Any chance you can reproduce and provide code/screenshots?

**Comment by jeffgreenca** [comment]
Will get back to you on this!  My test had a different result, but I will confirm and update.

**Comment by jeffgreenca** [comment]
I cannot reproduce.  Sorry for the distraction, must have been losing my mind when I tested this previously.
